# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Tested
version:      0.38
version_from: lib/HTML/Tested.pm
installdirs:  site
requires:
    Class::Accessor:               
    Class::Data::Inheritable:      
    Class::Singleton:              
    Crypt::Blowfish:               
    Crypt::CBC:                    2.22
    Data::Dumper:                  
    DateTime:                      
    DateTime::Format::Strptime:    
    Digest::CRC:                   
    File::Slurp:                   
    HTML::Entities:                
    Math::Combinatorics:           
    Template:                      
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
