--- #YAML:1.0
name:                HTML-Tested
version:             0.55
abstract:            This module allows creation of different HTML widgets with the built-in means of testing them
license:             ~
author:              
    - Boris Sukholitko (boriss@gmail.com)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor:               
    Class::Data::Inheritable:      
    Class::Singleton:              
    Crypt::Blowfish:               
    Crypt::CBC:                    2.22
    Data::Dumper:                  
    DateTime:                      
    DateTime::Format::Strptime:    
    Digest::CRC:                   
    File::Slurp:                   
    HTML::Entities:                
    Math::Combinatorics:           
    Template:                      
    Test::Simple:                  0.44
    Text::Diff:                    
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
